Inolist/Controllers/TaskController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InoList.Models.DataBase;
using InoList.Website.Core;
using InoList.Models.View;
using MailLibrary;

namespace InoList.Controllers
{
    [Authorize]
    public class TaskController : AbstractController
    {
        private readonly DataContext _db = new DataContext();

        //
        // GET: /Task/

        public ViewResult Index(String filter)
        {
            bool filterInput = false;
            bool filterOutput = false;
            switch (filter)
            {
                case "input":
                    filterOutput = true;
                    break;
                case "output":
                    filterInput = true;
                    break;
            }

            var userId = Session.User.Id;
            var tasks = _db.Tasks.Where(x => !x.IsArchival)
                           .Where(x => ((!filterOutput) && (x.AuthorID == userId ))
                                       || ((!filterInput) && x.ExecutorId == userId && x.AuthorID!= userId))
                           .Include(x => x.Author)
                           .Include(x => x.Executor)
                           .AsEnumerable();
            var tasksView = tasks.Select(x => new ViewTask(x)).OrderBy(x => x.EndDate, ViewTask.SortEndDate());


            return View(tasksView.ToList());
        }


        [HttpGet]
        public ActionResult Add()
        {
            AddSelectListExecutor(null);
            return PartialView("PopupAdd");
        }   

        [HttpPost]
        public ActionResult Add(TaskData taskdata)
        {
            if (ModelState.IsValid)
            {
                taskdata.CreateDate = DateTime.Now;
                taskdata.AuthorID = Session.User.Id;
                taskdata.Title = taskdata.Title.Trim();
                taskdata.Description = taskdata.Description.Trim();
                _db.Tasks.Add(taskdata);
                _db.SaveChanges();
                if (taskdata.ExecutorId != null && taskdata.ExecutorId != taskdata.AuthorID && taskdata.IsAlert)
                {
                    Mail.SetTaskExecutor(_db.Users.FirstOrDefault(x => x.Id == taskdata.ExecutorId).Email,
                                         Session.UserEmail,
                                         Session.User.FirstName + Session.User.LastName, taskdata.Title,
                                         taskdata.EndDate);
                }
                return RedirectToAction("Index");
            }
            AddSelectListExecutor(taskdata.ExecutorId);
            return PartialView("PopupAdd");
        }


        [HttpGet]
        public ActionResult Edit(Int32 id)
        {
            TaskData taskdata = _db.Tasks.Find(id);
            if (taskdata.AuthorID == Session.User.Id)
            {
                AddSelectListExecutor(taskdata.ExecutorId);
                return PartialView("PopupEditAuthor", taskdata);
            }
            return PartialView("PopupEditExecutor", taskdata);
        }

        [HttpPost]
        public ActionResult Edit(TaskData taskNew)
        {
            var taskPast = _db.Tasks.Find(taskNew.Id);
                if (taskPast.AuthorID == Session.User.Id)
                {
                    taskPast.Title = taskNew.Title.Trim();
                    taskPast.Description = taskNew.Description.Trim();
                    taskPast.EndDate = taskNew.EndDate;
                    taskPast.IsAlert = taskNew.IsAlert;
                    if (taskPast.IsAlert)
                    {
                        UserData executorNew = null;
                        UserData executorPast = null;
                        if (Session.User.Id != taskNew.ExecutorId && taskNew.ExecutorId != null)
                        {
                            executorNew = _db.Users.FirstOrDefault(x => x.Id == taskNew.ExecutorId);
                        }
                        if (Session.User.Id != taskPast.ExecutorId && taskPast.ExecutorId != null)
                        {
                            executorPast = _db.Users.FirstOrDefault(x => x.Id == taskPast.ExecutorId);
                        }
                        if (executorNew != executorPast)
                        {
                            if (executorNew != null)
                            {
                                Mail.SetTaskExecutor(executorNew.Email,
                                                     Session.UserEmail,
                                                     Session.User.FirstName +" " + Session.User.LastName, taskNew.Title,
                                                     taskNew.EndDate);
                            }
                            if (executorPast != null)
                            {
                                Mail.SetOffTaskExecutor(executorPast.Email,
                                                        Session.UserEmail,
                                                        Session.User.FirstName +" "+ Session.User.LastName, taskNew.Title,
                                                        taskNew.EndDate);
                            }
                        }
                        else
                        {
                            if (executorNew != null)
                            {
                                Mail.TaskEdit(executorNew.Email,
                                              Session.UserEmail,
                                              Session.User.FirstName + " "+Session.User.LastName, taskNew.Title);
                            }
                        }
                    }

                    taskPast.ExecutorId = taskNew.ExecutorId;
                }
                else
                {
                    taskPast.Description = taskNew.Description.Trim();
                    taskPast.EndDate = taskNew.EndDate;
                    Mail.TaskEdit(taskPast.Author.Email,
                                              Session.UserEmail,
                                              Session.User.FirstName +" " +Session.User.LastName, taskNew.Title);
 

                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            
        }


        [HttpDelete]
        public ActionResult Delete(Int32 id)
        {
            var task = _db.Tasks.FirstOrDefault(x => x.Id == id);
            if (task.AuthorID == Session.User.Id)
            {
                if (task.ExecutorId != null && task.ExecutorId != task.AuthorID && task.IsAlert)
                {
                    Mail.TaskDelete(task.Executor.Email, Session.UserEmail,
                                    Session.User.FirstName + " " + Session.User.LastName, task.Title);
                }
                _db.Tasks.Remove(task);
                _db.SaveChanges();
            }

            return new HttpStatusCodeResult(202);
        }


        [HttpPut]
        public HttpResponse Done(Int32 id)
        {
            var task = _db.Tasks.Find(id);
            if (task.ExecutorId != null && task.ExecutorId != task.AuthorID && task.IsAlert)
            {
                String email = Session.User.Id != task.ExecutorId ? task.Executor.Email : task.Author.Email;
                if (!task.IsDone)
                {
                    Mail.TaskDone(email, Session.UserEmail,
                                  Session.User.FirstName + " " + Session.User.LastName, task.Title);
                }
                else
                {
                    Mail.TaskReOpen(email, Session.UserEmail,
                                    Session.User.FirstName + " " + Session.User.LastName, task.Title);
                }
            }
            task.IsDone = !task.IsDone;
            _db.Entry(task).State = EntityState.Modified;
            _db.SaveChanges();
            return null;
        }

        [HttpPut]
        public HttpResponse Archive()
        {
            var tasks = _db.Tasks.Where(x => x.AuthorID == Session.User.Id && x.IsDone);
            if (tasks.Any())
            {
                foreach (var taskData in tasks)
                {
                    taskData.IsArchival = true;
                }
                _db.SaveChanges();
            }

            return null;
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }


             private void AddSelectListExecutor(Int32? id)
        {
            var team = _db.GetUserSelectList(Session.User.Id);
            ViewBag.ExecutorId =
                new SelectList(team.Select(x => new
                {    FullName =  x.FirstName + " " + x.LastName ,          
                   
                   Id = x.Id
                }), "Id", "FullName",id);
        }    
    }
}

Inolist/Controllers/TeamController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using InoList.Models.DataBase;
using InoList.Website.Core;
using InoList.Models.View;
using System.Data.Entity;
using InoList.Models;
using MailLibrary;

namespace InoList.Controllers
{
    [Authorize]
    public class TeamController : AbstractController
    {
        private readonly DataContext _db = new DataContext();

        public ActionResult Index(String filter)
        {
            var users =
                _db.Invites.Where(x => (x.SenderId == Session.User.Id || x.RecipientId == Session.User.Id) && (x.ExcludeId == null || Session.User.Id != x.ExcludeId))
                   .Include(x => x.Recipient)
                   .Include(x => x.Sender)
                   .AsEnumerable();
            var viewUser = users.Select(x => new ViewUser(x, Session.User.Id));

            bool filterEnable = false;
            bool filterTeam = false;
            switch (filter)
            {
                case "team":
                    filterEnable = true;
                    filterTeam = true;
                    break;
                case "notTeam":
                    filterEnable = true;
                    break;
            }
            if (filterEnable)
            {
                viewUser = viewUser.Where(x => x.Team == filterTeam);
            }
            return View(viewUser.ToList());
        }


        public ActionResult Add()
        {
            var model = new RegisterModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                String error = String.Empty;
                if (model.Email != Session.UserEmail)
                {
                    var team = _db.Invites.Where(x => x.SenderId == Session.User.Id || x.RecipientId == Session.User.Id);
                    bool isTeam = false;
                    bool isReSend = false;
                    if (team.Any())
                    {
                        isTeam =
                            team.Any(
                                x =>
                                (x.Recipient.Email == model.Email || x.Sender.Email == model.Email) &&
                                (x.ConfirmDate != null));
                        isReSend = team.Any(x => x.ResipientEmail == model.Email && x.RecipientId == null);
                    }

                    if (!isTeam)
                    {
                        if (!isReSend)
                        {
                            _db.Invites.Add(new Invites
                                {
                                    CreatedDate = DateTime.Now,
                                    ResipientEmail = model.Email,
                                    SenderId = Session.User.Id,
                                });
                            _db.SaveChanges();
                        }
                        if (!_db.Users.Any(x => x.Email == model.Email))
                        {
                            Mail.SendInvitesNewUser(model.Email, Session.User.Email,
                                                    Session.User.LastName + " " + Session.User.FirstName);
                        }
                        else
                        {
                            Mail.SendInvitesOldUser(model.Email, Session.User.Email,
                                                    Session.User.LastName + " " + Session.User.FirstName,
                                                    Session.User.Id);
                        }
                        return RedirectToAction("Index");
                    }
                    error = "Пользователь уже в команде";
                }
                else
                {
                    error = "Введите не свой email";
                }
                var modelReturn = new RegisterModel {Error = error};
                return View(modelReturn);
            }
            return View(new RegisterModel {Error = null});
        }


        public ActionResult Confirm(String email, Int32 senderId)
        {
            if (senderId != Session.User.Id && email==Session.UserEmail)
            {
                Invites invite = _db.Invites.First(x => x.ResipientEmail == email && x.SenderId == senderId);
                invite.ConfirmDate = DateTime.Now;
                invite.RecipientId = _db.Users.First(x => x.Email == email).Id;
                invite.ExcludeId = null;
                _db.Entry(invite).State = System.Data.EntityState.Modified;
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPut]
        public ActionResult Exclude(Int32 id)
        {
            var tasks = _db.Tasks.Where(x => x.ExecutorId == id && x.AuthorID == Session.User.Id && (!x.IsArchival));
            foreach (var task in tasks)
            {
                task.ExecutorId = null;
            }
            var invite = _db.Invites.First(x => x.RecipientId == id && x.SenderId == Session.User.Id
                                       || x.RecipientId == Session.User.Id && x.SenderId == id);
            invite.ConfirmDate = null;
            invite.CreatedDate = null;
            if (invite.SenderId != Session.User.Id)
            {
                invite.ResipientEmail= invite.Sender.Email;
                invite.RecipientId = invite.SenderId;
                invite.SenderId = Session.User.Id;
            }
            invite.ExcludeId = id;
            _db.SaveChanges();
            return new HttpStatusCodeResult(200);
        }

        [HttpPut]
        public ActionResult ReSend(String email)
        {
            var user = _db.Users.FirstOrDefault(x=>x.Email==email);
            if (user == null)
            {
                Mail.SendInvitesNewUser(email, Session.User.Email, Session.User.LastName +" "+ Session.User.FirstName);
            }
            else
            {
                Mail.SendInvitesOldUser(user.Email, Session.User.Email, Session.User.LastName +" "+ Session.User.FirstName, Session.User.Id);
            }

            var invite = _db.Invites.First(x=> x.SenderId == Session.User.Id || x.RecipientId == Session.User.Id);
            invite.CreatedDate = DateTime.Now;
            _db.SaveChanges();
            return new HttpStatusCodeResult(200);
        }


        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Inolist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <title>@ViewBag.Title</title>
 


    <link rel="stylesheet" media="all" href="@Url.Content("~/Content/custom.css")" />

    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.js")"></script>

    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/main.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.10.1.min.js")"></script>       
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
     <script src="@Url.Content("~/Scripts/jquery.validate.bootstrap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

</head>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">TaskList</a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Выйти", "LogOff", "Account", null, new { @class = "navbar-link" })
                        ;
                    }
                </p>
                <ul class="nav" id="navbar">
                    <li >@Html.ActionLink("Домой","Index","Task")</li>
                    <li>@Html.ActionLink("О проекте","About","Home")</li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<body>

    @RenderBody()

    <div class="modal hide" id="task-popup"></div>

</body>

<link rel="Stylesheet" media = "all" href="@Url.Content("~/Content/Site.css")" />
</html>

Inolist/Views/Shared/_LayoutWithOutScripts.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />

    <title>@ViewBag.Title</title>
 


    <link rel="stylesheet" media="all" href="@Url.Content("~/Content/bootstrap.css")" />
    <link rel="stylesheet" media="all" href="@Url.Content("~/Content/datepicker.css")" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/main.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.10.1.min.js")"></script>     
</head>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">TaskList</a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Выйти", "LogOff", "Account", null, new { @class = "navbar-link" })
                        ;
                    }
                </p>
                 <ul class="nav" id="navbar">
                    <li >@Html.ActionLink("Домой","Index","Task")</li>
                    <li>@Html.ActionLink("О проекте","About","Home")</li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<body>

    @RenderBody()

    <div class="modal hide" id="task-popup"></div>

</body>

<link rel="Stylesheet" media = "all" href="@Url.Content("~/Content/Site.css")" />
</html>

Inolist/Views/Shared/_Menu.cshtml


<ul class="nav nav-pills">
   <li>
    @Html.ActionLink("Задачи","Index","Task")
   </li>
  <li >
    @Html.ActionLink("Команда","Index","Team")
  </li>
</ul>